"""add quilt_type to album_quilt

Revision ID: 29a71b5b8e18
Revises: 3c267c9315ee
Create Date: 2026-08-15 23:13:42.201672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29a71b5b8e18'
down_revision: Union[str, Sequence[str], None] = '3c267c9315ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('albumquilt', sa.Column('quilt_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE albumquilt SET quilt_type = 'albums' WHERE quilt_type IS NULL")
    op.alter_column('albumquilt', 'quilt_type', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albumquilt', 'quilt_type')
    # ### end Alembic commands ###

